// <auto-generated />
using System;
using LemonAutomotives.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LemonAutomotives.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240929184742_ProductTableEdits")]
    partial class ProductTableEdits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CustomerStartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = new Guid("b4a7761a-c6f5-435f-bddb-e09550e4f14c"),
                            CustomerAddress = "4116 Franklin Avenue",
                            CustomerFirstName = "Judith",
                            CustomerLastName = "Marsh",
                            CustomerPhone = "3618758716",
                            CustomerStartDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerID = new Guid("9ffea449-4c4a-4ee3-9311-5f6fb05e3183"),
                            CustomerAddress = "3847 Burton Avenue",
                            CustomerFirstName = "Kimberly",
                            CustomerLastName = "Trombetta",
                            CustomerPhone = "9015978933",
                            CustomerStartDate = new DateTime(2023, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerID = new Guid("c79e9fb1-4454-427a-950f-7b2811cd5491"),
                            CustomerAddress = "2269 Rose Street",
                            CustomerFirstName = "Dennis",
                            CustomerLastName = "Sandoval",
                            CustomerPhone = "7082569698",
                            CustomerStartDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Products", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ProductCommission")
                        .HasColumnType("float");

                    b.Property<string>("ProductManufacturer")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ProductModel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double?>("ProductPurchasePrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.Property<string>("ProductYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("fec15166-ff7e-49a6-b404-aecdd6872cda"),
                            ProductCommission = 0.20000000000000001,
                            ProductManufacturer = "Fiat",
                            ProductModel = "500",
                            ProductName = "2012 Fiat 500",
                            ProductPurchasePrice = 5000.0,
                            ProductQty = 5,
                            ProductYear = "2012"
                        },
                        new
                        {
                            ProductID = new Guid("b9f2c219-8aff-4694-b405-2e7cde670758"),
                            ProductCommission = 0.089999999999999997,
                            ProductManufacturer = "Chrysler",
                            ProductModel = "300",
                            ProductName = "2015 Chrysler 300",
                            ProductPurchasePrice = 3000.0,
                            ProductQty = 2,
                            ProductYear = "2015"
                        },
                        new
                        {
                            ProductID = new Guid("32b4adb0-6c06-47ac-8ee8-bb3e4c14fe36"),
                            ProductCommission = 0.050000000000000003,
                            ProductManufacturer = "Jeep",
                            ProductModel = "Grand Cherokee",
                            ProductName = "2007 Jeep Grand Cherokee",
                            ProductPurchasePrice = 4000.0,
                            ProductQty = 1,
                            ProductYear = "2007"
                        });
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Sales", b =>
                {
                    b.Property<Guid>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SalespersonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SaleID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SalespersonID");

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            SaleID = new Guid("a6c0de2a-d93a-42f8-a3e9-c90711f98c6c"),
                            CustomerID = new Guid("b4a7761a-c6f5-435f-bddb-e09550e4f14c"),
                            ProductID = new Guid("fec15166-ff7e-49a6-b404-aecdd6872cda"),
                            SalesDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonID = new Guid("800c3eb8-a586-48e2-aeba-8fe3d0e20306")
                        },
                        new
                        {
                            SaleID = new Guid("6655a28d-cd0e-48dd-9eb4-ac3a1bbc9e1b"),
                            CustomerID = new Guid("9ffea449-4c4a-4ee3-9311-5f6fb05e3183"),
                            ProductID = new Guid("b9f2c219-8aff-4694-b405-2e7cde670758"),
                            SalesDate = new DateTime(2023, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonID = new Guid("496cee1e-59b5-4e2c-a6e9-ebfab5d3dd92")
                        },
                        new
                        {
                            SaleID = new Guid("efcaa7f0-0c41-44b4-a188-cc20781d23c1"),
                            CustomerID = new Guid("c79e9fb1-4454-427a-950f-7b2811cd5491"),
                            ProductID = new Guid("32b4adb0-6c06-47ac-8ee8-bb3e4c14fe36"),
                            SalesDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonID = new Guid("0890303a-b802-457a-b56e-aec2bfbead68")
                        });
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Salesperson", b =>
                {
                    b.Property<Guid>("SalespersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SalespersonAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SalespersonFirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalespersonLastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalespersonPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SalespersonStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SalespersonTerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SalespersonID");

                    b.ToTable("Salespersons", (string)null);

                    b.HasData(
                        new
                        {
                            SalespersonID = new Guid("800c3eb8-a586-48e2-aeba-8fe3d0e20306"),
                            SalespersonAddress = "2840 Gambler Lane",
                            SalespersonFirstName = "Hunter",
                            SalespersonLastName = "Lahr",
                            SalespersonPhone = "801-306-2352",
                            SalespersonStartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SalespersonID = new Guid("496cee1e-59b5-4e2c-a6e9-ebfab5d3dd92"),
                            SalespersonAddress = "2408 Hart Ridge Road",
                            SalespersonFirstName = "John",
                            SalespersonLastName = "Stewart",
                            SalespersonPhone = "201-395-1953",
                            SalespersonStartDate = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SalespersonID = new Guid("0890303a-b802-457a-b56e-aec2bfbead68"),
                            SalespersonAddress = "2949 Juniper Drive",
                            SalespersonFirstName = "Dennis",
                            SalespersonLastName = "Luczak",
                            SalespersonPhone = "814-393-4893",
                            SalespersonStartDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonTerminationDate = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SalespersonID = new Guid("3c8125d8-71d3-455a-99b9-93baf8b3f6dd"),
                            SalespersonAddress = "4291 Harley Vincent Drive",
                            SalespersonFirstName = "Debra",
                            SalespersonLastName = "Roger",
                            SalespersonPhone = "203-387-2069",
                            SalespersonStartDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Sales", b =>
                {
                    b.HasOne("LemonAutomotives.Core.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemonAutomotives.Core.Domain.Entities.Products", "Products")
                        .WithMany("Sales")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemonAutomotives.Core.Domain.Entities.Salesperson", "Salesperson")
                        .WithMany("Sales")
                        .HasForeignKey("SalespersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Products");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Products", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("LemonAutomotives.Core.Domain.Entities.Salesperson", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
